name: Python Package using Conda

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Run a Python script
      run: python .github/workflows/a.py
